// my-react-app/src/pages/Home.tsx
import { useState } from 'react'
import '../styles/Home.css'

interface ActivityItem {
  id: number
  type: 'mentor' | 'donation' | 'job'
  title: string
  description: string
  timeAgo: string
  icon: string
}

interface HomeProps {
  onNavigate: (page: string) => void
  onLogout: () => void
}

export default function Home({ onNavigate, onLogout }: HomeProps) {
  const [activities] = useState<ActivityItem[]>([
    {
      id: 1,
      type: 'mentor',
      title: 'New Mentor Message',
      description: 'Dr. Reyes replied to your inquiry about...',
      timeAgo: '15m ago',
      icon: '👤'
    },
    {
      id: 2,
      type: 'donation',
      title: 'Donation Receipt Ready',
      description: 'Thank you for your contribution to the...',
      timeAgo: '2h ago',
      icon: '💝'
    },
    {
      id: 3,
      type: 'job',
      title: 'Job Application Update',
      description: 'Your application for "Project Manager" wa...',
      timeAgo: '1d ago',
      icon: '💼'
    }
  ])

  return (
    <div className="home-container">
      {/* Header */}
      <div className="home-header">
        <div className="header-top">
          <button className="menu-btn">☰</button>
          <button className="profile-btn">👤</button>
        </div>
        <div className="greeting-section">
          <p className="welcome-text">Welcome back,</p>
          <h1 className="greeting">Hello, Alex</h1>
          <div className="illustration">👨‍💼</div>
        </div>
      </div>

      {/* Quick Navigation */}
      <div className="quick-nav">
        <button className="nav-btn">Network</button>
        <button 
          className="nav-btn"
          onClick={() => onNavigate('donate')}
        >
          Donate
        </button>
        <button 
          className="nav-btn"
          onClick={() => onNavigate('career')}
        >
          Career
        </button>
        <button className="nav-btn">Docs</button>
        <button className="nav-btn search-btn">🔍</button>
      </div>

      {/* Scrollable Content */}
      <div style={{ flex: 1, overflowY: 'auto', overflowX: 'hidden' }}>
        {/* Daily Snapshot */}
        <div className="daily-snapshot">
          <h2>Your Daily Snapshot</h2>
          <div className="snapshot-grid">
            <div className="snapshot-card">
              <div className="snapshot-icon">💼</div>
              <h3>Jobs for You</h3>
              <p className="snapshot-value">5</p>
              <p className="snapshot-label">new matches</p>
            </div>
            <div className="snapshot-card">
              <div className="snapshot-icon">✓</div>
              <h3>Verified Status</h3>
              <p className="snapshot-value">95%</p>
              <p className="snapshot-label">Profile</p>
            </div>
          </div>
        </div>

        {/* Recent Activity */}
        <div className="recent-activity">
          <div className="activity-header">
            <h2>Your Recent Activity</h2>
            <a href="#" className="view-all">View All</a>
          </div>

          <div className="activity-list">
            {activities.map((activity) => (
              <div key={activity.id} className="activity-item">
                <div className={`activity-icon type-${activity.type}`}>
                  {activity.icon}
                </div>
                <div className="activity-content">
                  <h3>{activity.title}</h3>
                  <p>{activity.description}</p>
                </div>
                <div className="activity-time">{activity.timeAgo}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Bottom Navigation */}
      <nav className="bottom-nav">
        <button className="nav-item active">
          <span className="nav-icon">🏠</span>
          <span className="nav-label">Home</span>
        </button>
        <button className="nav-item">
          <span className="nav-icon">👥</span>
          <span className="nav-label">Network</span>
        </button>
        <button 
          className="nav-item"
          onClick={() => onNavigate('donate')}
        >
          <span className="nav-icon">💝</span>
          <span className="nav-label">Donate</span>
        </button>
        <button className="nav-item">
          <span className="nav-icon">💼</span>
          <span className="nav-label">Career</span>
        </button>
        <button 
          className="nav-item"
          onClick={onLogout}
        >
          <span className="nav-icon">📄</span>
          <span className="nav-label">Documents</span>
        </button>
      </nav>
    </div>
  )
}

// src/components/Home.vue
<template>
  <div class="home-container">
    <div class="header">
      <h1>Hello, Alex!</h1>
      <p class="subtitle">Welcome back</p>
    </div>

    <!-- Daily Snapshot Section -->
    <section class="snapshot-section">
      <h2>Your Daily Snapshot</h2>
      <div class="snapshot-grid">
        <div class="snapshot-card">
          <div class="snapshot-icon">💼</div>
          <div class="snapshot-content">
            <p class="snapshot-label">Jobs for You</p>
            <p class="snapshot-value">8 new matches</p>
          </div>
        </div>
        <div class="snapshot-card">
          <div class="snapshot-icon">✓</div>
          <div class="snapshot-content">
            <p class="snapshot-label">Verified Status</p>
            <p class="snapshot-value">Profile 35%</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Recent Activity Section -->
    <section class="activity-section">
      <h2>Your Recent Activity</h2>
      <div class="view-all">
        <a href="#" class="view-all-link">View All</a>
      </div>

      <div class="activity-list">
        <div class="activity-item">
          <div class="activity-icon">💬</div>
          <div class="activity-content">
            <p class="activity-title">New Member Message</p>
            <p class="activity-description">Hi, there! replied to your message about...</p>
            <p class="activity-time">1m ago</p>
          </div>
        </div>

        <div class="activity-item">
          <div class="activity-icon">🎁</div>
          <div class="activity-content">
            <p class="activity-title">Donation Receipt Ready</p>
            <p class="activity-description">Thank you for your contribution to...</p>
            <p class="activity-time">2h ago</p>
          </div>
        </div>

        <div class="activity-item">
          <div class="activity-icon">📢</div>
          <div class="activity-content">
            <p class="activity-title">Job Application Update</p>
            <p class="activity-description">Your application for "Project Manager" is...</p>
            <p class="activity-time">1d ago</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Quick Navigation Pills -->
    <section class="quick-nav-section">
      <h2>Quick Access</h2>
      <div class="pills-container">
        <button 
          v-for="pill in quickNavPills"
          :key="pill.id"
          class="pill-button"
          @click="navigateTo(pill.id)"
        >
          <span class="pill-icon">{{ pill.icon }}</span>
          <span>{{ pill.label }}</span>
        </button>
      </div>
    </section>

    <!-- Spacer for bottom nav -->
    <div class="bottom-spacer"></div>
  </div>
</template>

<script setup>
defineProps({
  onNavigate: Function
});

const quickNavPills = [
  { id: 'network', label: 'Browse Alumni', icon: '👥' },
  { id: 'career', label: 'Job Board', icon: '💼' },
  { id: 'donate', label: 'Support Initiatives', icon: '❤️' },
  { id: 'documents', label: 'View Documents', icon: '📄' }
];

const navigateTo = (pageId) => {
  // This will be handled by parent component
  console.log('Navigate to:', pageId);
};
</script>

<style scoped>
.home-container {
  padding: 24px;
  max-width: 1024px;
  margin: 0 auto;
}

.header {
  margin-bottom: 32px;
  padding-top: 12px;
}

.header h1 {
  font-size: 48px;
  margin: 0 0 8px 0;
  color: var(--text-h);
}

.subtitle {
  color: var(--text);
  font-size: 16px;
  margin: 0;
}

/* Snapshot Section */
.snapshot-section {
  margin-bottom: 40px;
}

.snapshot-section h2 {
  margin-bottom: 16px;
  font-size: 20px;
}

.snapshot-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
}

.snapshot-card {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 20px;
  border: 1px solid var(--border);
  border-radius: 12px;
  background: var(--bg);
  transition: all 0.2s ease;
}

.snapshot-card:hover {
  border-color: var(--accent);
  background: var(--accent-bg);
}

.snapshot-icon {
  font-size: 32px;
  flex-shrink: 0;
}

.snapshot-content {
  flex: 1;
}

.snapshot-label {
  font-size: 14px;
  color: var(--text);
  margin: 0 0 4px 0;
}

.snapshot-value {
  font-size: 18px;
  font-weight: 600;
  color: var(--text-h);
  margin: 0;
}

/* Activity Section */
.activity-section {
  margin-bottom: 40px;
}

.activity-section h2 {
  margin-bottom: 12px;
  font-size: 20px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.view-all {
  margin-bottom: 16px;
}

.view-all-link {
  font-size: 14px;
  color: var(--accent);
  text-decoration: none;
  transition: all 0.2s ease;
}

.view-all-link:hover {
  text-decoration: underline;
}

.activity-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.activity-item {
  display: flex;
  gap: 16px;
  padding: 16px;
  border: 1px solid var(--border);
  border-radius: 12px;
  background: var(--bg);
  cursor: pointer;
  transition: all 0.2s ease;
}

.activity-item:hover {
  border-color: var(--accent);
  background: var(--accent-bg);
}

.activity-icon {
  font-size: 28px;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 48px;
  height: 48px;
  border-radius: 8px;
  background: var(--accent-bg);
}

.activity-content {
  flex: 1;
}

.activity-title {
  font-size: 16px;
  font-weight: 600;
  color: var(--text-h);
  margin: 0 0 4px 0;
}

.activity-description {
  font-size: 14px;
  color: var(--text);
  margin: 0 0 8px 0;
  line-height: 1.4;
}

.activity-time {
  font-size: 12px;
  color: var(--text);
  margin: 0;
  opacity: 0.7;
}

/* Quick Navigation Section */
.quick-nav-section {
  margin-bottom: 40px;
}

.quick-nav-section h2 {
  margin-bottom: 16px;
  font-size: 20px;
}

.pills-container {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
}

.pill-button {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px 20px;
  border: 1px solid var(--border);
  border-radius: 24px;
  background: var(--bg);
  color: var(--text-h);
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s ease;
  white-space: nowrap;
}

.pill-button:hover {
  border-color: var(--accent);
  background: var(--accent-bg);
  color: var(--accent);
}

.pill-icon {
  font-size: 18px;
}

/* Spacer for bottom nav */
.bottom-spacer {
  height: 100px;
}

@media (max-width: 640px) {
  .home-container {
    padding: 16px;
  }

  .header h1 {
    font-size: 36px;
  }

  .snapshot-grid {
    grid-template-columns: 1fr;
  }

  .pills-container {
    flex-direction: column;
  }

  .pill-button {
    width: 100%;
    justify-content: center;
  }
}
</style>
